# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jlehideu <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/16 10:06:02 by jlehideu          #+#    #+#              #
#    Updated: 2017/08/19 10:23:52 by jlehideu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op

SOURCES = main.c ft_atoi.c basics.c operations.c

all : $(NAME)

$(NAME):
	gcc -o $(NAME) $(SRC)

clean:
	rm $(NAME)
