# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jlehideu <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/20 17:00:22 by jlehideu          #+#    #+#              #
#    Updated: 2017/08/21 10:26:45 by jlehideu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SOURCES = display.c\
		  basics.c

all: $(NAME)

$(NAME): 
	gcc -o $(NAME) $(SOURCES)

clean:
	rm $(NAME)

re: clean all
